version: '3'

services:
  sqlxmigrate:
    image: sqlxmigrate
    depends_on:
      - postgresql
      - mysql
    environment:
      PGPASSWORD: postgres
      PG_CONN_STRING: host=postgresql user=postgres password=postgres dbname=sqlxmigrate_test port=5432 sslmode=disable
      MYSQL_CONN_STRING: root:mysql@tcp(mysql)/sqlxmigrate_test?multiStatements=true

  postgresql:
    image: postgres:11.2
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: sqlxmigrate_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sqlxmigrate_test
      MYSQL_ROOT_PASSWORD: mysql

